version: '3.8'

services:
  app:
    build: ./app
    ports:
      - "80:80"
    environment:
      MARIADB_HOST: "db"
      MARIADB_USERNAME: "root"
      MARIADB_ROOT_PASSWORD: "password"
    volumes:
      - ./app/src:/var/www/html
    restart: always
  db:
    build: ./database
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: "password"
    volumes:
      - db_data:/var/lib/mysql
    restart: always

volumes:
  db_data: {}
